"""Add idempotency replay columns

Revision ID: 285ffd425e88
Revises: 74d6b6e8ca88
Create Date: 2026-08-21 23:11:27.984917
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '285ffd425e88'
down_revision: Union[str, None] = '74d6b6e8ca88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_ledger', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.add_column('usage_ledger', sa.Column('response_status_code', sa.Integer(), nullable=True))
    op.add_column('usage_ledger', sa.Column('response_body', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.drop_constraint(op.f('usage_ledger_request_id_key'), 'usage_ledger', type_='unique')
    op.create_unique_constraint('uq_usage_tenant_idempotency', 'usage_ledger', ['tenant_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_usage_tenant_idempotency', 'usage_ledger', type_='unique')
    op.create_unique_constraint(op.f('usage_ledger_request_id_key'), 'usage_ledger', ['request_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('usage_ledger', 'response_body')
    op.drop_column('usage_ledger', 'response_status_code')
    op.drop_column('usage_ledger', 'idempotency_key')
    # ### end Alembic commands ###
