"""fix usage ledger status constraint

Revision ID: 300167f02bfa
Revises: 508bdae8f537
Create Date: 2026-08-23 11:57:35.560724
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '300167f02bfa'
down_revision: Union[str, None] = '508bdae8f537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chk_usage_status', 'usage_ledger', type_='check')
    op.create_check_constraint('chk_usage_status', 'usage_ledger', "status IN ('pending', 'completed', 'failed', 'partial')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chk_usage_status', 'usage_ledger', type_='check')
    op.create_check_constraint('chk_usage_status', 'usage_ledger', "status IN ('completed', 'failed', 'partial')")
    # ### end Alembic commands ###
