"""add claimed_at to usage_ledger

Revision ID: 508bdae8f537
Revises: 72c36cd4315a
Create Date: 2026-08-22 15:41:56.862827
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '508bdae8f537'
down_revision: Union[str, None] = '72c36cd4315a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_ledger', sa.Column('claimed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usage_ledger', 'claimed_at')
    # ### end Alembic commands ###
