"""add claimed_at to usage_ledger

Revision ID: 72c36cd4315a
Revises: 285ffd425e88
Create Date: 2026-08-22 15:39:54.658633
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '72c36cd4315a'
down_revision: Union[str, None] = '285ffd425e88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
