"""add status check constraints

Revision ID: 74d6b6e8ca88
Revises: 6bbb25586ed8
Create Date: 2026-08-21 13:34:41.329065
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '74d6b6e8ca88'
down_revision: Union[str, None] = '6bbb25586ed8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('job_status_check', 'jobs', "status IN ('pending', 'processing', 'completed', 'failed', 'dead_letter')")
    op.create_check_constraint('webhook_status_check', 'webhook_deliveries', "status IN ('pending', 'completed', 'failed')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('webhook_status_check', 'webhook_deliveries', type_='check')
    op.drop_constraint('job_status_check', 'jobs', type_='check')
    # ### end Alembic commands ###
